# Generated by Django 6.0.7 on 2026-08-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_postcomment_is_flagged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('warned', 'Warned'), ('hidden', 'Content hidden'), ('deleted', 'Content deleted'), ('banned', 'User banned')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('reason', models.CharField(choices=[('spam', 'Spam or scam'), ('harassment', 'Harassment or bullying'), ('misinformation', 'Misinformation'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_hidden', 'Auto-hidden'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('action_taken', models.CharField(blank=True, choices=[('', 'None'), ('hidden', 'Content hidden'), ('deleted', 'Content deleted'), ('warned', 'Author warned'), ('banned', 'Author banned')], default='', max_length=12)),
                ('admin_note', models.TextField(blank=True, help_text='Private note for the moderator reviewing this report.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.postcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('reporter', 'post'), name='unique_report_post_per_user'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='unique_report_comment_per_user')],
            },
        ),
    ]
