# Generated by Django 6.0.7 on 2026-08-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_postcomment_is_flagged'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content_snapshot',
            field=models.TextField(blank=True, help_text='Snapshot of the reported content so the audit trail survives deletion.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Null after the comment is deleted; the original text is kept in the snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='community.postcomment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Null after the post is deleted; the original text is kept in the snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='community.post'),
        ),
    ]
