# Generated by Django 4.2.16 on 2026-06-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesubmission',
            name='cooking_time',
            field=models.IntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipesubmission',
            name='preparation_time',
            field=models.IntegerField(default=0, help_text='Time in minutes'),
        ),
    ]
