# Generated by Django 4.2.16 on 2026-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_recipesubmission_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesubmission',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipesubmission',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='recipesubmission',
            name='cook_hours',
            field=models.IntegerField(default=0, help_text='Cooking hours'),
        ),
        migrations.AddField(
            model_name='recipesubmission',
            name='cook_minutes',
            field=models.IntegerField(default=0, help_text='Cooking minutes'),
        ),
        migrations.AddField(
            model_name='recipesubmission',
            name='cook_seconds',
            field=models.IntegerField(default=0, help_text='Cooking seconds'),
        ),
        migrations.AddField(
            model_name='recipesubmission',
            name='prep_hours',
            field=models.IntegerField(default=0, help_text='Preparation hours'),
        ),
        migrations.AddField(
            model_name='recipesubmission',
            name='prep_minutes',
            field=models.IntegerField(default=0, help_text='Preparation minutes'),
        ),
        migrations.AddField(
            model_name='recipesubmission',
            name='prep_seconds',
            field=models.IntegerField(default=0, help_text='Preparation seconds'),
        ),
        migrations.AlterField(
            model_name='recipesubmission',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
