# Generated by Django 6.0.7 on 2026-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_recipesubmission_cooking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
