# Generated by Django 6.0.7 on 2026-09-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_recipesubmission_meal_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesubmission',
            name='video_url',
        ),
    ]
