# Generated by Django 6.0.7 on 2026-08-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
