# Generated by Django 4.2.16 on 2026-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_value',
            field=models.IntegerField(default=0, help_text='Number of time units'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_value',
            field=models.IntegerField(default=0, help_text='Number of time units'),
        ),
    ]
