# Generated by Django 4.2.16 on 2026-06-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time_value',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time_value',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_hours',
            field=models.IntegerField(default=0, help_text='Cooking hours'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_minutes',
            field=models.IntegerField(default=0, help_text='Cooking minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_seconds',
            field=models.IntegerField(default=0, help_text='Cooking seconds'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_hours',
            field=models.IntegerField(default=0, help_text='Preparation hours'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_minutes',
            field=models.IntegerField(default=0, help_text='Preparation minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_seconds',
            field=models.IntegerField(default=0, help_text='Preparation seconds'),
        ),
    ]
