# Generated by Django 6.0.7 on 2026-07-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_cooking_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
