# Generated by Django 6.0.7 on 2026-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_types',
            field=models.JSONField(blank=True, default=list, help_text='When this recipe is normally eaten. List of breakfast/lunch/dinner; empty = any time.'),
        ),
    ]
