# Generated by Django 6.0.7 on 2026-09-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_meal_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video_url',
        ),
    ]
