// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-lkFfOOr2RItCSq30WkqyUTbbDioeNyY',
    appId: '1:191937303536:web:8f9b6475b60be3f6b94335',
    messagingSenderId: '191937303536',
    projectId: 'sudanile-5b766',
    authDomain: 'sudanile-5b766.firebaseapp.com',
    storageBucket: 'sudanile-5b766.firebasestorage.app',
    measurementId: 'G-G106JD53VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsGgj5aRjdIF9Tu_skaFARML2h7DJDmE',
    appId: '1:191937303536:android:8704607b30df2f42b94335',
    messagingSenderId: '191937303536',
    projectId: 'sudanile-5b766',
    storageBucket: 'sudanile-5b766.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoz7TEtDuZC7lqOp8xSwVa8nBdtrfMBNg',
    appId: '1:684504206283:ios:c02efcfd0e6970168bc44e',
    messagingSenderId: '684504206283',
    projectId: 'junubin-211',
    storageBucket: 'junubin-211.firebasestorage.app',
    iosBundleId: 'com.example.sudanileKitchen',
  );
}
