// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ61Dnuy_rstV6VBOMmZoLjGFOa4kfNxw',
    appId: '1:684504206283:web:fed75cc378e5e4038bc44e',
    messagingSenderId: '684504206283',
    projectId: 'junubin-211',
    authDomain: 'junubin-211.firebaseapp.com',
    storageBucket: 'junubin-211.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxG8EiFlnOStkYl7mm7VBx04AZVPSFx-A',
    appId: '1:684504206283:android:7c503f1bccbaa8688bc44e',
    messagingSenderId: '684504206283',
    projectId: 'junubin-211',
    storageBucket: 'junubin-211.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoz7TEtDuZC7lqOp8xSwVa8nBdtrfMBNg',
    appId: '1:684504206283:ios:c02efcfd0e6970168bc44e',
    messagingSenderId: '684504206283',
    projectId: 'junubin-211',
    storageBucket: 'junubin-211.firebasestorage.app',
    iosBundleId: 'com.example.sudanileKitchen',
  );
}
